spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: mypass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8282